### ISSUE TITLE
PermissionError: [WinError 10013]

### ISSUE THREAD

**Issue by pynbbz** [dylnbk/youtube-download#1]
While trying to run the .exe version on a local machine, there's following error and app stops running.
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by dylnbk** [comment]
I believe this could be due to your firewall, antivirus or possibly admin rights (privileges/permissions).

As this .exe runs a web server on your machine, it will need administrator rights and port 8501 should also be open.
